CREATE DATABASE shoppingmall;

CREATE TABLE `tb_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(32) NOT NULL COMMENT '密码，加密存储',
  `phone` varchar(20) DEFAULT NULL COMMENT '注册手机号',
  `email` varchar(50) DEFAULT NULL COMMENT '注册邮箱',
  `created` datetime NOT NULL COMMENT '创建时间',
  `updated` datetime NOT NULL,
  `source_type` varchar(1) DEFAULT NULL COMMENT '会员来源：1:PC，2：H5，3：Android，4：IOS，5：WeChat',
  `nick_name` varchar(50) DEFAULT NULL COMMENT '昵称',
  `name` varchar(50) DEFAULT NULL COMMENT '真实姓名',
  `status` varchar(1) DEFAULT NULL COMMENT '使用状态（Y正常 N非正常）',
  `head_pic` varchar(150) DEFAULT NULL COMMENT '头像地址',
  `qq` varchar(20) DEFAULT NULL COMMENT 'QQ号码',
  `account_balance` decimal(10,0) DEFAULT NULL COMMENT '账户余额',
  `is_mobile_check` varchar(1) DEFAULT '0' COMMENT '手机是否验证 （0否  1是）',
  `is_email_check` varchar(1) DEFAULT '0' COMMENT '邮箱是否检测（0否  1是）',
  `sex` varchar(1) DEFAULT '0' COMMENT '性别，1男，2女',
  `user_level` int(11) DEFAULT NULL COMMENT '会员等级',
  `points` int(11) DEFAULT NULL COMMENT '积分',
  `experience_value` int(11) DEFAULT NULL COMMENT '经验值',
  `birthday` datetime DEFAULT NULL COMMENT '生日',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` USING BTREE (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `tb_order` (
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `payment` decimal(20,2) DEFAULT NULL COMMENT '实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `payment_type` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '支付类型，1、在线支付，2、货到付款',
  `post_fee` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分',
  `status` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '状态：1、未付款，2、已付款，3、未发货，4、已发货，5、交易成功，6、交易关闭,7、待评价',
  `create_time` datetime DEFAULT NULL COMMENT '订单创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '订单更新时间',
  `payment_time` datetime DEFAULT NULL COMMENT '付款时间',
  `consign_time` datetime DEFAULT NULL COMMENT '发货时间',
  `end_time` datetime DEFAULT NULL COMMENT '交易完成时间',
  `close_time` datetime DEFAULT NULL COMMENT '交易关闭时间',
  `shipping_name` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '物流名称',
  `shipping_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '物流单号',
  `user_id` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '用户id',
  `buyer_message` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '买家留言',
  `buyer_nick` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '买家昵称',
  `buyer_rate` varchar(2) COLLATE utf8_bin DEFAULT NULL COMMENT '买家是否已经评价',
  `receiver_area_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '收货人地区名称(省，市，县)街道',
  `receiver_mobile` varchar(12) COLLATE utf8_bin DEFAULT NULL COMMENT '收货人手机',
  `receiver_zip_code` varchar(15) COLLATE utf8_bin DEFAULT NULL COMMENT '收货人邮编',
  `receiver` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT '收货人',
  `expire` datetime DEFAULT NULL COMMENT '过期时间，定期清理',
  `invoice_type` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '发票类型(普通发票，电子发票，增值税发票)',
  `source_type` varchar(1) COLLATE utf8_bin DEFAULT NULL COMMENT '订单来源：1:app端，2：pc端，3：M端，4：微信端，5：手机qq端',
  `seller_id` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '商家ID',
  PRIMARY KEY (`order_id`),
  KEY `create_time` (`create_time`),
  KEY `buyer_nick` (`buyer_nick`),
  KEY `status` (`status`),
  KEY `payment_type` (`payment_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (1,NULL,'1',NULL,'0','2017-08-24 20:42:25','2017-08-24 20:42:25',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (2,NULL,'1',NULL,'0','2017-08-24 20:44:03','2017-08-24 20:44:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (3,'3.00','1',NULL,'0','2017-08-24 20:46:10','2017-08-24 20:46:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (4,'266.64','1',NULL,'0','2017-08-24 20:46:11','2017-08-24 20:46:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (5,'299.97','1',NULL,'0','2017-08-24 20:46:11','2017-08-24 20:46:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (6,'3.00','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (7,'266.64','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (8,'299.97','1',NULL,'0','2017-08-24 20:46:40','2017-08-24 20:46:40',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (9,'3.00','1',NULL,'0','2017-08-24 21:01:10','2017-08-24 21:01:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (10,'266.64','1',NULL,'0','2017-08-24 21:01:11','2017-08-24 21:01:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (11,'299.97','1',NULL,'0','2017-08-24 21:01:11','2017-08-24 21:01:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (12,'3.00','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (13,'266.64','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (14,'299.97','1',NULL,'0','2017-08-24 21:05:56','2017-08-24 21:05:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (15,'3.00','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (16,'266.64','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (17,'299.97','1',NULL,'0','2017-08-24 23:07:38','2017-08-24 23:07:38',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (18,'177.76','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (19,'2.00','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (20,'177.76','1',NULL,'1','2017-08-25 11:59:03','2017-08-25 11:59:03',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (21,'177.76','1',NULL,'1','2017-08-25 23:26:10','2017-08-25 23:26:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (22,'2.00','1',NULL,'1','2017-08-25 23:26:11','2017-08-25 23:26:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (23,'177.76','1',NULL,'1','2017-08-25 23:26:11','2017-08-25 23:26:11',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (24,'2.00','1',NULL,'1','2017-08-25 23:28:10','2017-08-25 23:28:10',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (25,'1.00','1',NULL,'1','2017-08-25 23:49:18','2017-08-25 23:49:18',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (26,'0.01','1',NULL,'1','2017-08-26 00:06:31','2017-08-26 00:06:31',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'修正大厦','13700221122',NULL,'李佳红',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (27,'0.01','1',NULL,'1','2017-08-26 00:10:13','2017-08-26 00:10:13',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (28,'0.01','1',NULL,'1','2017-08-26 00:17:53','2017-08-26 00:17:53',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (29,'0.01','1',NULL,'1','2017-08-26 00:19:56','2017-08-26 00:19:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (30,'0.01','1',NULL,'1','2017-08-26 00:37:47','2017-08-26 00:37:47',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (31,'0.02','1',NULL,'1','2017-08-26 00:37:47','2017-08-26 00:37:47',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (32,'0.02','1',NULL,'2','2017-08-26 00:41:13','2017-08-26 00:41:13',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (33,'0.01','1',NULL,'2','2017-08-26 00:41:14','2017-08-26 00:41:14',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,NULL);
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (34,'0.01','1',NULL,'1','2017-08-26 11:57:26','2017-08-26 11:57:26',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (35,'0.01','1',NULL,'1','2017-08-26 12:21:39','2017-08-26 12:21:39',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (36,'0.01','1',NULL,'1','2017-08-26 12:34:46','2017-08-26 12:34:46',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (37,'0.01','1',NULL,'2','2017-08-26 12:47:44','2017-08-26 12:47:44',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (38,'0.02','1',NULL,'2','2017-08-26 12:47:44','2017-08-26 12:47:44',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'yijia');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918159799198212096,'400.00','1',NULL,'1','2017-10-12 01:02:09','2017-10-12 01:02:09',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'咏春武馆总部','999111',NULL,'叶问',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918334996291301376,'2004.00','2',NULL,'1','2017-10-12 12:38:19','2017-10-12 12:38:19',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'永春武馆','11011011',NULL,'李小龙',NULL,NULL,'2','qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918334996698148864,'1798.00','2',NULL,'1','2017-10-12 12:38:19','2017-10-12 12:38:19',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'永春武馆','11011011',NULL,'李小龙',NULL,NULL,'2','yijia');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918773289399160832,'200.00','1',NULL,'1','2017-10-13 17:39:56','2017-10-13 17:39:56',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'永春武馆','11011011',NULL,'李小龙',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918780408353546240,'0.01','1',NULL,'2','2017-10-13 18:08:14','2017-10-13 18:08:14',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'永春武馆','11011011',NULL,'李小龙',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918806410454654976,'0.01','1',NULL,'2','2017-10-13 19:51:33','2017-10-13 19:51:33',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918833485639081984,'0.01','1',NULL,'1','2017-10-13 21:39:08','2017-10-13 21:39:08',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (918835712441212928,'0.01','1',NULL,'2','2017-10-13 21:47:59','2017-10-13 21:47:59',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,NULL,'qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (919055624854081536,'0.01','1',NULL,'1','2017-10-14 12:21:50','2017-10-14 12:21:50',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'中腾大厦','13301212233',NULL,'李佳星',NULL,NULL,'2','qiandu');
insert  into `tb_order`(`order_id`,`payment`,`payment_type`,`post_fee`,`status`,`create_time`,`update_time`,`payment_time`,`consign_time`,`end_time`,`close_time`,`shipping_name`,`shipping_code`,`user_id`,`buyer_message`,`buyer_nick`,`buyer_rate`,`receiver_area_name`,`receiver_mobile`,`receiver_zip_code`,`receiver`,`expire`,`invoice_type`,`source_type`,`seller_id`) values (919059760869863424,'0.02','1',NULL,'2','2017-10-14 12:38:16','2017-10-14 12:38:16',NULL,NULL,NULL,NULL,NULL,NULL,'lijialong',NULL,NULL,NULL,'金燕龙办公楼','13900112222',NULL,'李嘉诚',NULL,NULL,'2','qiandu');